Cls_data()
Video("+")

@  7,7 SAY empr->nombre
@  9,7 SAY empr->direccion
@ 11,7 SAY empr->dnrp
@ 13,7 SAY empr->actividad
@ 16,7 SAY empr->Hsferiado

Video()

@  6, 3 SAY "Empresa :"
@  8, 3 SAY "Direccion:"
@ 10, 3 SAY "DRP"
@ 12, 3 SAY "Actividad"
@ 15, 3 SAY "Horas feriado (8-9)"



* --------- Para Multiempresa ----------- *
*W_rec()
*@ 14,66 TO 20,78
*@ 15,68 SAY "Codigo :"
*@ 16,68 SAY empr->cod

