@  6, 23  GET  pers->NOMBRE PICT "@!"
@  6, 68  GET  pers->LEGAJO
*@  8, 14  GET  pers->CATEGORIA
*@  8, 61  GET  pers->CALIFPROF
@ 10, 12  GET  pers->INGRESO
@ 10, 32  GET  pers->EGRESO
@ 10, 64  GET  pers->INGRESO_RE
@ 12, 22  GET  pers->NUMAFILIAD
@ 12,45 GET PERS->CONVENIO VALID(CONVENIO $ "UA")
@ 12, 75  GET  pers->SUEJOR PICT "@!" valid(suejor $ "SJ")
@ 14, 23  GET  pers->NACION PICT "@!" valid(nacion $ "AE")
@ 14, 64  GET  pers->DOC_TIPO  PICT "@!A"
@ 14, 68  GET  pers->DOC_NUM
@ 16, 17  get  pers->est_civil PICT "@!A"
@ 16, 64  get  pers->decl_jur

@ 19, 20  GET  pers->MESES_TRAB
@ 19, 43  GET  pers->AC_ANUAL
@ 19, 62  GET  pers->AC_ANIO

